baseURL = "https://blog.olivame.xyz"
languageCode = "en-us"
title = "Yuzhi Deng's homepage"
theme = "PaperMod"

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
disableSpecial1stPost = true
ShowReadingTime = true
ShowBreadCrumbs = true
showPostNavLinks = true

# é¦–é¡µç®€ä»‹å¡ç‰‡
#[params.homeInfoParams]
#Title = "Hiï¼Œæˆ‘æ˜¯ Yuzhi Deng ğŸ‘‹"
#Content = "æ¬¢è¿æ¥åˆ°æˆ‘çš„ä¸ªäººä¸»é¡µã€‚æˆ‘å–œæ¬¢ AIã€æŠ€æœ¯ç ”ç©¶å’Œæ•ˆç‡å·¥å…·ã€‚"
